sudo: required
services:
 - docker
  
before_install:
 - gem update --system
 - gem --version
 - docker build -t dheerajmportal/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true dheerajmportal/multi-docker-test npm run test

after_success:
 - docker build -t dheerajmportal/multi-worker ./worker
 - docker build -t dheerajmportal/multi-client ./client
 - docker build -t dheerajmportal/multi-api ./server
 - docker build -t dheerajmportal/multi-nginx ./nginx
#Login to docker-cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# take those images and push into docker hub
 - docker push dheerajmportal/multi-nginx
 - docker push dheerajmportal/multi-client
 - docker push dheerajmportal/multi-api
 - docker push dheerajmportal/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "multi-docker"
 env: "Multidocker-env" 
 bucket_name: "elasticbeanstalk-us-east-1-133701099257"
 bucket_path: "docker-multi"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"
 skip_cleanup: true

